version: "3.2"
services:
  web:
    image: tinder-for-food
    depends_on:
      - db
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.2"
          memory: 64M
      restart_policy:
        condition: "on-failure"
    ports:
      - 5001:5000
    networks:
      - webnet
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0

  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "tinder_for_food"
      POSTGRES_USER: "tinder_for_food_user"
      POSTGRES_PASSWORD: "tinder_for_food_password"
    networks:
      - webnet
    deploy:
      restart_policy:
        condition: "on-failure"

  adminer:
    image: adminer
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: "on-failure"
    ports:
      - 8080:8080
    networks:
      - webnet
networks:
  webnet:
